# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZpDxsS11zj28N3hBBTgJYJgaINOe2ekr

# Ejercicios
"""

import numpy as np
import random as rd
matriz =np.random.randint(100, size=(3,3))
print(matriz)
print("El promedio de los elementos es:", matriz.mean())
print("La suma de los elementos es:", matriz.sum())
print("El numero mayor es:", matriz.max())
print("El numero menor es:", matriz.min())
print("Los numeros de la matriz en diagonal son:",
      matriz[0,0],matriz[1,1],matriz[2,2])
